import React, { useState, useCallback, useMemo } from 'react';
import { SEVERITY_META, CATEGORY_LABELS } from './mlAuditMeta';

/**
 * MLRemediationPanel — Stage 14: ModelLens Remediation Panel.
 *
 * Renders the Stage 13 MLAuditIssue selected from a hazard gutter marker:
 *  - severity / category / title / message
 *  - offending_code   — the exact source the audit flagged
 *  - remediation_code — the corrected pattern (deterministic, generated by Stage 13)
 *  - explanation      — why it is a problem
 *
 * Includes prev/next navigation across every issue in the trace and a
 * copy-to-clipboard action for the remediation snippet.
 *
 * The remediation snippet is rendered verbatim from the backend — no live LLM
 * call is made on click, so the panel is instant and works offline.
 */

export default function MLRemediationPanel({
  issues = [],
  selectedIssue = null,
  onSelectIssue,
}) {
  const [copied, setCopied] = useState(false);

  const selectedIndex = useMemo(() => {
    if (!selectedIssue) return -1;
    return issues.findIndex((i) => i.issue_id === selectedIssue.issue_id);
  }, [issues, selectedIssue]);

  const handleCopy = useCallback(async (text) => {
    if (!text) return;
    try {
      if (navigator?.clipboard?.writeText) {
        await navigator.clipboard.writeText(text);
      } else {
        // Fallback for non-HTTPS or restricted clipboard permissions
        const textarea = document.createElement('textarea');
        textarea.value = text;
        textarea.style.position = 'fixed';
        textarea.style.opacity = '0';
        document.body.appendChild(textarea);
        textarea.select();
        document.execCommand('copy');
        document.body.removeChild(textarea);
      }
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    } catch {
      // Clipboard unavailable — leave the snippet visible for manual selection.
    }
  }, []);

  const goTo = useCallback(
    (delta) => {
      if (issues.length === 0 || !onSelectIssue) return;
      const base = selectedIndex >= 0 ? selectedIndex : 0;
      const next = (base + delta + issues.length) % issues.length;
      onSelectIssue(issues[next]);
    },
    [issues, selectedIndex, onSelectIssue]
  );

  // ── Empty state ──────────────────────────────────────────────────────────
  if (issues.length === 0) {
    return (
      <div className="flex flex-col h-full gap-3">
        <PanelHeader issueCount={0} />
        <div className="flex flex-col items-center justify-center flex-1 gap-2 text-slate-600 text-center px-4">
          <span className="text-2xl" aria-hidden="true">
            ✓
          </span>
          <span className="text-xs font-mono font-semibold text-emerald-400/80">
            No methodology issues found
          </span>
          <span className="text-[11px] text-slate-600 leading-relaxed">
            The Stage 13 diagnostics engine found no data leakage, class imbalance,
            preprocessing mismatch, or metric mismatch in this trace.
          </span>
        </div>
      </div>
    );
  }

  if (!selectedIssue) {
    return (
      <div className="flex flex-col h-full gap-3">
        <PanelHeader issueCount={issues.length} />
        <div className="flex flex-col items-center justify-center flex-1 gap-2 text-slate-600 text-center px-4">
          <span className="text-2xl" aria-hidden="true">
            ☠
          </span>
          <span className="text-xs font-mono font-semibold text-slate-400">
            Select a hazard marker
          </span>
          <span className="text-[11px] text-slate-600 leading-relaxed">
            Click a hazard stripe in the code gutter to inspect the flagged line and its
            remediation.
          </span>
        </div>

        {/* Full issue index so the panel is useful before any marker is clicked */}
        <div className="px-4 pb-4">
          <IssueIndex issues={issues} onSelectIssue={onSelectIssue} />
        </div>
      </div>
    );
  }

  const meta = SEVERITY_META[selectedIssue.severity] ?? SEVERITY_META.info;
  const categoryLabel = CATEGORY_LABELS[selectedIssue.category] ?? selectedIssue.category;

  return (
    <div className="flex flex-col h-full min-h-0">
      <PanelHeader issueCount={issues.length} onBack={() => onSelectIssue && onSelectIssue(null)} />

      {/* Prev / next navigation */}
      <div className="shrink-0 flex items-center justify-between gap-2 px-4 py-1.5 bg-slate-900/60 border-b border-slate-800">
        <button
          type="button"
          onClick={() => goTo(-1)}
          className="px-2 py-0.5 rounded text-[11px] font-mono text-slate-400 hover:text-slate-100 hover:bg-slate-700/60 transition-colors cursor-pointer"
          title="Previous issue"
        >
          ← Prev
        </button>
        <span className="text-[10px] font-mono text-slate-500">
          {selectedIndex >= 0 ? selectedIndex + 1 : 1} of {issues.length}
        </span>
        <button
          type="button"
          onClick={() => goTo(1)}
          className="px-2 py-0.5 rounded text-[11px] font-mono text-slate-400 hover:text-slate-100 hover:bg-slate-700/60 transition-colors cursor-pointer"
          title="Next issue"
        >
          Next →
        </button>
      </div>

      {/* Issue detail */}
      <div className="flex-1 overflow-y-auto p-4 flex flex-col gap-3 min-h-0">
        {/* Severity + category + line */}
        <div className="flex flex-wrap items-center gap-1.5">
          <span
            className={`px-2 py-0.5 rounded-md border text-[10px] font-mono font-bold uppercase tracking-wider ${meta.chip}`}
          >
            {meta.label}
          </span>
          <span className="px-2 py-0.5 rounded-md bg-slate-800/70 border border-slate-700/60 text-[10px] font-mono text-slate-300">
            {categoryLabel}
          </span>
          <span className="px-2 py-0.5 rounded-md bg-slate-800/70 border border-slate-700/60 text-[10px] font-mono text-slate-400">
            line {selectedIssue.line_number}
          </span>
        </div>

        <h3 className="text-xs font-bold text-slate-100 leading-snug">
          {selectedIssue.title}
        </h3>

        <p className="text-[11px] text-slate-400 leading-relaxed">
          {selectedIssue.message}
        </p>

        {/* Offending code */}
        <CodeBlock
          label="Offending code"
          code={selectedIssue.offending_code}
          tone="danger"
        />

        {/* Remediation code */}
        <CodeBlock
          label="Corrected pattern"
          code={selectedIssue.remediation_code}
          tone="safe"
          onCopy={() => handleCopy(selectedIssue.remediation_code)}
          copied={copied}
        />

        {/* Why it matters */}
        {selectedIssue.explanation && (
          <div className="rounded-lg border border-slate-800 bg-slate-950/60 p-3">
            <div className="text-[10px] font-mono uppercase tracking-wider text-slate-500 mb-1.5">
              Why this matters
            </div>
            <p className="text-[11px] text-slate-400 leading-relaxed">
              {selectedIssue.explanation}
            </p>
          </div>
        )}

        <IssueIndex issues={issues} onSelectIssue={onSelectIssue} activeId={selectedIssue.issue_id} />
      </div>
    </div>
  );
}

/* ── Sub-components ─────────────────────────────────────────────────────── */

function PanelHeader({ issueCount, onBack }) {
  return (
    <div className="shrink-0 flex items-center justify-between border-b border-slate-800 px-4 pt-4 pb-2.5">
      <div className="flex items-center gap-2">
        {onBack && (
          <button
            type="button"
            onClick={onBack}
            className="text-slate-400 hover:text-slate-200 text-xs font-mono px-1.5 py-0.5 rounded hover:bg-slate-800 transition-colors mr-1 cursor-pointer"
            title="Back to all findings"
          >
            ←
          </button>
        )}
        <span className="text-rose-400 font-bold text-base leading-none" aria-hidden="true">
          ☠
        </span>
        <span className="text-xs font-semibold text-slate-200 font-mono">Remediation</span>
      </div>
      <span className="text-[10px] font-mono text-slate-500 bg-slate-800/60 border border-slate-700/50 px-2 py-0.5 rounded">
        {issueCount} issue{issueCount !== 1 ? 's' : ''}
      </span>
    </div>
  );
}

function CodeBlock({ label, code, tone, onCopy, copied }) {
  if (!code) return null;
  const toneClasses =
    tone === 'danger'
      ? 'border-red-900/60 bg-red-950/20'
      : 'border-emerald-900/60 bg-emerald-950/20';
  const labelColor = tone === 'danger' ? 'text-red-300/80' : 'text-emerald-300/80';

  return (
    <div className={`rounded-lg border overflow-hidden ${toneClasses}`}>
      <div className="flex items-center justify-between px-2.5 py-1 bg-slate-900/50 border-b border-slate-800/60">
        <span className={`text-[10px] font-mono uppercase tracking-wider ${labelColor}`}>
          {label}
        </span>
        {onCopy && (
          <button
            type="button"
            onClick={onCopy}
            className="px-1.5 py-0.5 rounded text-[10px] font-mono font-semibold text-slate-400 hover:text-emerald-300 hover:bg-slate-700/60 transition-colors cursor-pointer"
            title="Copy to clipboard"
          >
            {copied ? '✓ Copied' : 'Copy'}
          </button>
        )}
      </div>
      <pre className="p-2.5 text-[11px] font-mono text-slate-200 leading-5 overflow-x-auto whitespace-pre">
        {code}
      </pre>
    </div>
  );
}

function IssueIndex({ issues, onSelectIssue, activeId }) {
  if (!onSelectIssue) return null;
  return (
    <div className="rounded-lg border border-slate-800 bg-slate-950/40 p-2.5">
      <div className="text-[10px] font-mono uppercase tracking-wider text-slate-500 mb-1.5">
        All findings
      </div>
      <ul className="flex flex-col gap-1">
        {issues.map((issue) => {
          const m = SEVERITY_META[issue.severity] ?? SEVERITY_META.info;
          const isActive = issue.issue_id === activeId;
          return (
            <li key={issue.issue_id}>
              <button
                type="button"
                onClick={() => onSelectIssue(issue)}
                className={`w-full text-left flex items-start gap-2 px-2 py-1.5 rounded transition-colors cursor-pointer ${
                  isActive ? 'bg-slate-800/80 ring-1 ring-slate-600/60' : 'hover:bg-slate-800/50'
                }`}
              >
                <span className={`w-1.5 h-1.5 rounded-full mt-1 shrink-0 ${m.dot}`} aria-hidden="true" />
                <span className="min-w-0 flex-1">
                  <span className="block text-[11px] font-mono text-slate-200 truncate">
                    L{issue.line_number} · {issue.title}
                  </span>
                </span>
              </button>
            </li>
          );
        })}
      </ul>
    </div>
  );
}
